---
- name: install software applications
  hosts: all
  tasks:
    - name: install software applications
      apt: 
        name: "{{a}}"
        state: "{{b}}"
        update_cache: "{{c}}"
...          
