---
- name: create users and files
  hosts: all
  tasks:
    - name: create users
      user:
        name: "{{a}}"
        password: "{{b}}"
        home: "{{c}}"
    - name: create file
      file: 
        name: "{{d}}"
        state: "{{e}}"
...
  
